spring:
  profiles: 'default'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    schema:
      - classpath:db/schema_drop.sql
      - classpath:db/schema.sql
    data:
      - classpath:db/data.sql

server:
  port: 8080
  servlet:
    context-path: /